const config = require('config')

window.onload = function (e) {
  // Using a Promise object
  liff
    .init({
      liffId: config.config.liffId // use own liffId
    })
    .then(() => {
      // Start to use liff's api
      initializeApp()
    })
    .catch((err) => {
      // Error happens during initialization
      console.log(err.code, err.message);
    });
};


/**
* Display data generated by invoking LIFF methods
*/
function displayLiffData() {
  document.getElementById('browserLanguage').textContent = liff.getLanguage();
  document.getElementById('sdkVersion').textContent = liff.getVersion();
  document.getElementById('isInClient').textContent = liff.isInClient();
  document.getElementById('isLoggedIn').textContent = liff.isLoggedIn();
  document.getElementById('deviceOS').textContent = liff.getOS();
}


function initializeApp(data) {
  // if (!liff.isLoggedIn()) {
  //   // set `redirectUri` to redirect the user to a URL other than the front page of your LIFF app.
  //   liff.login();
  // }
  // login call, only when external browser is used
  document.getElementById('liffLoginButton').addEventListener('click', function () {
    if (!liff.isLoggedIn()) {
      // set `redirectUri` to redirect the user to a URL other than the front page of your LIFF app.
      liff.login();
    }
  });


  // logout call only when external browse
  document.getElementById('liffLogoutButton').addEventListener('click', function () {
    if (liff.isLoggedIn()) {
      liff.logout();
      window.location.reload();
    }
  });


  // openWindow call
  document.getElementById('openWindowButton').addEventListener('click', function () {
    liff.openWindow({
      url: 'https://line.me',
      external: true
    });
  });


  // scanCode call
  document.getElementById('scanQrCodeButton').addEventListener('click', function () {
    if (!liff.isInClient()) {
      sendAlertIfNotInClient();
    } else {
      liff.scanCode().then(result => {
        // e.g. result = { value: "Hello LIFF app!" }
        const stringifiedResult = JSON.stringify(result);
        document.getElementById('scanQrField').textContent = stringifiedResult;
        toggleQrCodeReader();
      }).catch(err => {
        document.getElementById('scanQrField').textContent = "scanCode failed!";
      });
    }
  });

  // get access token
  document.getElementById('getAccessToken').addEventListener('click', function () {
    if (!liff.isLoggedIn() && !liff.isInClient()) {
      alert('To get an access token, you need to be logged in. Please tap the "login" button below and try again.');
    } else {
      const accessToken = liff.getAccessToken();
      document.getElementById('accessTokenField').textContent = accessToken;
      toggleAccessToken();
    }
  });

  // get profile call
  document.getElementById('getProfileButton').addEventListener('click', function () {
    liff.getProfile().then(function (profile) {
      document.getElementById('userIdProfileField').textContent = profile.userId;
      document.getElementById('displayNameField').textContent = profile.displayName;

      const profilePictureDiv = document.getElementById('profilePictureDiv');
      if (profilePictureDiv.firstElementChild) {
        profilePictureDiv.removeChild(profilePictureDiv.firstElementChild);
      }
      const img = document.createElement('img');
      img.src = profile.pictureUrl;
      img.alt = 'Profile Picture';
      profilePictureDiv.appendChild(img);

      document.getElementById('statusMessageField').textContent = profile.statusMessage;
      toggleProfileData();
    }).catch(function (error) {
      window.alert('Error getting profile: ' + error);
    });
  });

  // sendMessages call
  document.getElementById('sendMessageButton').addEventListener('click', function () {
    if (!liff.isInClient()) {
      sendAlertIfNotInClient();
    } else {
      liff.sendMessages([{
        'type': 'text',
        'text': "You've successfully sent a message! Hooray!"
      }]).then(function () {
        window.alert('Message sent');
      }).catch(function (error) {
        window.alert('Error sending message: ' + error);
      });
    }
  });

  // closeWindow call
  document.getElementById('closeWindowButton').addEventListener('click', function () {
    if (!liff.isInClient()) {
      sendAlertIfNotInClient();
    } else {
      liff.closeWindow();
    }
  });

  displayLiffData()
};